### ISSUE TITLE
Deployment script hangs on "Creating the Web PubSub that enables real-time update of ACS Agent Hub Portal"

### ISSUE THREAD

**Issue by KonstantinLS** [managedcoder/ACSAgentHub#1]
Hi
Deployment script hangs on "Creating the Web PubSub that enables real-time update of ACS Agent Hub Portal":
![deploy](https://user-images.githubusercontent.com/94699941/142695708-a6ab559b-3405-47d0-a7d1-178aeaf558dc.png)

There is an error in deploy_log.txt file:
AZ CLI passes minimum version. Current version is 2.30.0
WARNING: Setting SCM_DO_BUILD_DURING_DEPLOYMENT to false
WARNING: Waiting SCM site to be updated with the latest app settings
WARNING: Getting scm site credentials for zip deployment
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [Errno 2] No such file or directory: 'C:\\ACSAgentHub\\ACSAgentHubPublish.zip'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 403, in enable_zip_deploy_functionapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 433, in enable_zip_deploy
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ACSAgentHub\\ACSAgentHubPublish.zip'
To open an issue, please run: 'az feedback'

**Comment by KonstantinLS** [comment]
Deployment script hangs on "Creating the Web PubSub that enables real-time update of ACS Agent Hub Portal"
the reason is Web PubSub extension was not installed. In my case it should be installed with
`az extension add --name webpubsub`

ERROR: [Errno 2] No such file or directory: 'C:\ACSAgentHub\ACSAgentHubPublish.zip' still in place

**Comment by managedcoder** [comment]
Can you add `-showCommands true` to the `deploy_and_configure.ps1` command in Step 2 of the README? This will print a trace of the deployment commands as they execute with fully expanded argument values and that will help in understanding what's happening.  There is also a log file called `deploy_log.txt` in the Deployment folder which could shed some light on what is happening.

**Comment by managedcoder** [comment]
I am going to close this issue since the prerequisites state that Web PubSub CLI Extension is required and how to install it.  I can reopen this issue if I've misunderstood things here.
